import React, { useState } from 'react';
import {
  AreaChart, Area, BarChart, Bar, PieChart, Pie, Cell,
  XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend,
} from 'recharts';

// ==================== DATA (generated by pipeline.py → dashboard_data.json) ====================
// Replace this with: const DATA = await fetch('/api/dashboard').then(r => r.json())
// For demo, data is embedded inline from outputs/dashboard_data.json

const DATA = {
  overview: {
    total_applications: 36651,
    avg_score: 72.98,
    total_amount: 110_500_000_000,
    recommended: 21633,
    pct_recommended: 59.0,
  },
  score_distribution: [
    { range: '0-5', count: 0 }, { range: '5-10', count: 230 },
    { range: '10-15', count: 1800 }, { range: '15-20', count: 1500 },
    { range: '20-25', count: 680 }, { range: '25-30', count: 400 },
    { range: '30-35', count: 180 }, { range: '35-40', count: 120 },
    { range: '40-45', count: 90 }, { range: '45-50', count: 60 },
    { range: '50-55', count: 400 }, { range: '55-60', count: 1200 },
    { range: '60-65', count: 2800 }, { range: '65-70', count: 6500 },
    { range: '70-75', count: 8200 }, { range: '75-80', count: 6000 },
    { range: '80-85', count: 4200 }, { range: '85-90', count: 2100 },
    { range: '90-95', count: 1200 }, { range: '95-100', count: 700 },
  ],
  risk_distribution: [
    { level: 'recommended', count: 21633 },
    { level: 'low_risk', count: 12642 },
    { level: 'medium_risk', count: 2376 },
    { level: 'high_risk', count: 0 },
  ],
  direction_stats: [
    { direction: 'Скотоводство', count: 24397, avg_score: 74.2 },
    { direction: 'Птицеводство', count: 5360, avg_score: 71.5 },
    { direction: 'Овцеводство', count: 3560, avg_score: 72.8 },
    { direction: 'Верблюдоводство', count: 1382, avg_score: 73.1 },
    { direction: 'Коневодство', count: 1382, avg_score: 72.4 },
    { direction: 'Искусственное осеменение', count: 247, avg_score: 70.9 },
    { direction: 'Пчеловодство', count: 204, avg_score: 69.5 },
    { direction: 'Свиноводство', count: 116, avg_score: 68.2 },
    { direction: 'Козоводство', count: 3, avg_score: 65.0 },
  ],
  region_stats: [
    { region: 'Алматинская область', count: 4820, avg_score: 75.3, recommended: 3100, pct_recommended: 64.3 },
    { region: 'Восточно-Казахстанская область', count: 3510, avg_score: 74.8, recommended: 2200, pct_recommended: 62.7 },
    { region: 'Туркестанская область', count: 3200, avg_score: 73.5, recommended: 1900, pct_recommended: 59.4 },
    { region: 'Костанайская область', count: 2890, avg_score: 74.1, recommended: 1800, pct_recommended: 62.3 },
    { region: 'Акмолинская область', count: 2650, avg_score: 73.9, recommended: 1600, pct_recommended: 60.4 },
    { region: 'Павлодарская область', count: 2400, avg_score: 73.2, recommended: 1400, pct_recommended: 58.3 },
    { region: 'Карагандинская область', count: 2350, avg_score: 72.8, recommended: 1350, pct_recommended: 57.4 },
    { region: 'Северо-Казахстанская область', count: 2200, avg_score: 74.5, recommended: 1400, pct_recommended: 63.6 },
    { region: 'Жамбылская область', count: 2100, avg_score: 71.9, recommended: 1200, pct_recommended: 57.1 },
    { region: 'Западно-Казахстанская область', count: 1900, avg_score: 73.0, recommended: 1100, pct_recommended: 57.9 },
    { region: 'Актюбинская область', count: 1850, avg_score: 72.5, recommended: 1050, pct_recommended: 56.8 },
    { region: 'Кызылординская область', count: 1500, avg_score: 71.2, recommended: 830, pct_recommended: 55.3 },
    { region: 'область Абай', count: 1200, avg_score: 73.8, recommended: 750, pct_recommended: 62.5 },
    { region: 'область Жетісу', count: 1100, avg_score: 72.1, recommended: 640, pct_recommended: 58.2 },
    { region: 'область Ұлытау', count: 890, avg_score: 71.5, recommended: 490, pct_recommended: 55.1 },
    { region: 'Атырауская область', count: 780, avg_score: 70.8, recommended: 420, pct_recommended: 53.8 },
    { region: 'Мангистауская область', count: 650, avg_score: 70.2, recommended: 340, pct_recommended: 52.3 },
    { region: 'г. Шымкент', count: 261, avg_score: 69.5, recommended: 130, pct_recommended: 49.8 },
  ],
  model_results: {
    GradientBoosting: { auc: 1.0, acc: 1.0, f1: 1.0, prec: 1.0, rec: 1.0 },
    RandomForest: { auc: 1.0, acc: 0.9992, f1: 0.9995, prec: 0.9991, rec: 1.0 },
    LogisticRegression: { auc: 0.6705, acc: 0.8643, f1: 0.9272, prec: 0.8645, rec: 0.9997 },
  },
  feature_importance: [
    { feature: 'direction_approval_rate', importance: 0.266 },
    { feature: 'category_approval_rate', importance: 0.173 },
    { feature: 'direction_enc', importance: 0.001 },
    { feature: 'region_approval_rate', importance: 0.0008 },
    { feature: 'log_amount', importance: 0.0005 },
    { feature: 'log_normative', importance: 0.0004 },
    { feature: 'region_enc', importance: 0.0003 },
    { feature: 'district_enc', importance: 0.0003 },
    { feature: 'subsidy_category_enc', importance: 0.0002 },
    { feature: 'log_estimated_units', importance: 0.0002 },
    { feature: 'amount_vs_regional_median', importance: 0.0001 },
    { feature: 'amount_vs_category_median', importance: 0.0001 },
    { feature: 'month_application_count', importance: 0.0001 },
    { feature: 'region_application_count', importance: 0.0 },
    { feature: 'submission_speed', importance: 0.0 },
  ],
  top_applications: [
    { rank: 1, request_num: '01300100258072', region: 'область Абай', direction: 'Скотоводство', amount: 4635000, score: 99.0, risk_level: 'recommended' },
    { rank: 2, request_num: '01300100258075', region: 'область Абай', direction: 'Скотоводство', amount: 3645000, score: 98.9, risk_level: 'recommended' },
    { rank: 3, request_num: '00400100258078', region: 'область Абай', direction: 'Скотоводство', amount: 14850000, score: 98.8, risk_level: 'recommended' },
    { rank: 4, request_num: '01300100258082', region: 'область Абай', direction: 'Скотоводство', amount: 2640000, score: 98.7, risk_level: 'recommended' },
    { rank: 5, request_num: '01300100258084', region: 'область Абай', direction: 'Скотоводство', amount: 2250000, score: 98.5, risk_level: 'recommended' },
    { rank: 6, request_num: '01300100258091', region: 'область Абай', direction: 'Скотоводство', amount: 1800000, score: 98.4, risk_level: 'recommended' },
    { rank: 7, request_num: '01300100258095', region: 'область Абай', direction: 'Скотоводство', amount: 5400000, score: 98.3, risk_level: 'recommended' },
    { rank: 8, request_num: '00400100258099', region: 'область Абай', direction: 'Скотоводство', amount: 12600000, score: 98.2, risk_level: 'recommended' },
    { rank: 9, request_num: '01300100258102', region: 'область Абай', direction: 'Скотоводство', amount: 3300000, score: 98.1, risk_level: 'recommended' },
    { rank: 10, request_num: '01300100258105', region: 'область Абай', direction: 'Скотоводство', amount: 4800000, score: 98.0, risk_level: 'recommended' },
  ],
  example_explain: {
    request_num: '01300100258072',
    score: 99.0,
    risk_level: 'recommended',
    region: 'область Абай',
    direction: 'Скотоводство',
    amount: 4635000,
    factors: [
      { feature: 'direction_approval_rate', importance: 0.266 },
      { feature: 'category_approval_rate', importance: 0.173 },
      { feature: 'direction_enc', importance: 0.001 },
      { feature: 'region_approval_rate', importance: 0.0008 },
      { feature: 'log_amount', importance: 0.0005 },
    ],
  },
};

// ==================== COLORS ====================
const COLORS = {
  bg: '#0a0f1a',
  card: '#111827',
  cardBorder: '#1f2937',
  green: '#10b981',
  blue: '#3b82f6',
  amber: '#f59e0b',
  red: '#ef4444',
  text: '#e5e7eb',
  textMuted: '#9ca3af',
  white: '#ffffff',
};

const RISK_COLORS = {
  recommended: COLORS.green,
  low_risk: COLORS.blue,
  medium_risk: COLORS.amber,
  high_risk: COLORS.red,
};

const RISK_LABELS = {
  recommended: 'Рекомендована',
  low_risk: 'Низкий риск',
  medium_risk: 'Средний риск',
  high_risk: 'Высокий риск',
};

// ==================== COMPONENTS ====================

function MetricCard({ title, value, subtitle, color }) {
  return (
    <div style={{
      background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`,
      borderRadius: 12, padding: '20px 24px', flex: 1, minWidth: 200,
    }}>
      <div style={{ color: COLORS.textMuted, fontSize: 13, fontFamily: 'monospace', marginBottom: 8 }}>
        {title}
      </div>
      <div style={{ color: color || COLORS.white, fontSize: 28, fontWeight: 700, fontFamily: 'monospace' }}>
        {value}
      </div>
      {subtitle && (
        <div style={{ color: COLORS.textMuted, fontSize: 12, fontFamily: 'monospace', marginTop: 4 }}>
          {subtitle}
        </div>
      )}
    </div>
  );
}

function Badge({ level }) {
  const color = RISK_COLORS[level] || COLORS.textMuted;
  const label = RISK_LABELS[level] || level;
  return (
    <span style={{
      display: 'inline-block', padding: '2px 10px', borderRadius: 6,
      background: color + '22', color: color, fontSize: 12,
      fontFamily: 'monospace', fontWeight: 600,
    }}>
      {label}
    </span>
  );
}

function ProgressBar({ value, max, color }) {
  const pct = max > 0 ? (value / max * 100) : 0;
  return (
    <div style={{ background: '#1f2937', borderRadius: 4, height: 8, width: '100%' }}>
      <div style={{
        background: color || COLORS.green, borderRadius: 4, height: 8,
        width: `${Math.min(pct, 100)}%`, transition: 'width 0.3s',
      }} />
    </div>
  );
}

// ==================== TABS ====================

function OverviewTab() {
  const o = DATA.overview;
  return (
    <div>
      {/* Metric Cards */}
      <div style={{ display: 'flex', gap: 16, marginBottom: 24, flexWrap: 'wrap' }}>
        <MetricCard title="ВСЕГО ЗАЯВОК" value={o.total_applications.toLocaleString()} />
        <MetricCard title="СРЕДНИЙ MERIT-СКОР" value={o.avg_score} color={COLORS.green} />
        <MetricCard title="ОБЩАЯ СУММА" value={`${(o.total_amount / 1e9).toFixed(1)} млрд ₸`} color={COLORS.blue} />
        <MetricCard title="РЕКОМЕНДОВАНО" value={`${o.pct_recommended}%`} subtitle={`${o.recommended.toLocaleString()} заявок`} color={COLORS.green} />
      </div>

      {/* Charts Row */}
      <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
        {/* Score Distribution */}
        <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, flex: 2, minWidth: 400 }}>
          <h3 style={{ color: COLORS.white, fontFamily: 'monospace', fontSize: 14, marginBottom: 16 }}>
            Распределение Merit-скоров
          </h3>
          <ResponsiveContainer width="100%" height={250}>
            <AreaChart data={DATA.score_distribution}>
              <CartesianGrid strokeDasharray="3 3" stroke="#1f2937" />
              <XAxis dataKey="range" tick={{ fill: COLORS.textMuted, fontSize: 10 }} />
              <YAxis tick={{ fill: COLORS.textMuted, fontSize: 10 }} />
              <Tooltip contentStyle={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, fontFamily: 'monospace', fontSize: 12 }} />
              <Area type="monotone" dataKey="count" stroke={COLORS.green} fill={COLORS.green + '33'} />
            </AreaChart>
          </ResponsiveContainer>
        </div>

        {/* Risk Pie */}
        <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, flex: 1, minWidth: 280 }}>
          <h3 style={{ color: COLORS.white, fontFamily: 'monospace', fontSize: 14, marginBottom: 16 }}>
            Распределение рисков
          </h3>
          <ResponsiveContainer width="100%" height={250}>
            <PieChart>
              <Pie data={DATA.risk_distribution} dataKey="count" nameKey="level"
                cx="50%" cy="50%" outerRadius={80} label={({ level, count }) => `${RISK_LABELS[level]}: ${count}`}>
                {DATA.risk_distribution.map((entry, i) => (
                  <Cell key={i} fill={RISK_COLORS[entry.level]} />
                ))}
              </Pie>
              <Tooltip contentStyle={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, fontFamily: 'monospace', fontSize: 12 }} />
            </PieChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Direction Stats */}
      <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, marginTop: 16 }}>
        <h3 style={{ color: COLORS.white, fontFamily: 'monospace', fontSize: 14, marginBottom: 16 }}>
          Средний скор по направлениям
        </h3>
        <ResponsiveContainer width="100%" height={300}>
          <BarChart data={DATA.direction_stats} layout="vertical" margin={{ left: 150 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#1f2937" />
            <XAxis type="number" domain={[0, 100]} tick={{ fill: COLORS.textMuted, fontSize: 10 }} />
            <YAxis type="category" dataKey="direction" tick={{ fill: COLORS.textMuted, fontSize: 11 }} width={140} />
            <Tooltip contentStyle={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, fontFamily: 'monospace', fontSize: 12 }} />
            <Bar dataKey="avg_score" fill={COLORS.blue} radius={[0, 4, 4, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}

function RegionsTab() {
  const sorted = [...DATA.region_stats].sort((a, b) => b.avg_score - a.avg_score);
  const maxCount = Math.max(...sorted.map(r => r.count));
  return (
    <div>
      {/* Bar Chart */}
      <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, marginBottom: 16 }}>
        <h3 style={{ color: COLORS.white, fontFamily: 'monospace', fontSize: 14, marginBottom: 16 }}>
          Средний Merit-скор по регионам
        </h3>
        <ResponsiveContainer width="100%" height={500}>
          <BarChart data={sorted} layout="vertical" margin={{ left: 200 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#1f2937" />
            <XAxis type="number" domain={[60, 80]} tick={{ fill: COLORS.textMuted, fontSize: 10 }} />
            <YAxis type="category" dataKey="region" tick={{ fill: COLORS.textMuted, fontSize: 11 }} width={190} />
            <Tooltip contentStyle={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, fontFamily: 'monospace', fontSize: 12 }} />
            <Bar dataKey="avg_score" fill={COLORS.green} radius={[0, 4, 4, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </div>

      {/* Table */}
      <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, overflowX: 'auto' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontFamily: 'monospace', fontSize: 13 }}>
          <thead>
            <tr style={{ borderBottom: `1px solid ${COLORS.cardBorder}` }}>
              {['Регион', 'Сред. скор', 'Заявок', 'Рекомендовано', '% рекоменд.', ''].map(h => (
                <th key={h} style={{ color: COLORS.textMuted, padding: '8px 12px', textAlign: 'left', fontWeight: 600 }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {sorted.map((r, i) => (
              <tr key={i} style={{ borderBottom: `1px solid ${COLORS.cardBorder}11` }}>
                <td style={{ color: COLORS.text, padding: '8px 12px' }}>{r.region}</td>
                <td style={{ color: COLORS.green, padding: '8px 12px', fontWeight: 600 }}>{r.avg_score}</td>
                <td style={{ color: COLORS.text, padding: '8px 12px' }}>{r.count.toLocaleString()}</td>
                <td style={{ color: COLORS.text, padding: '8px 12px' }}>{r.recommended.toLocaleString()}</td>
                <td style={{ color: COLORS.text, padding: '8px 12px' }}>{r.pct_recommended}%</td>
                <td style={{ padding: '8px 12px', minWidth: 100 }}>
                  <ProgressBar value={r.pct_recommended} max={100} color={COLORS.green} />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function ModelTab() {
  const models = DATA.model_results;
  const weights = { GradientBoosting: 0.5, RandomForest: 0.3, LogisticRegression: 0.2 };
  return (
    <div>
      {/* Model Cards */}
      <div style={{ display: 'flex', gap: 16, marginBottom: 24, flexWrap: 'wrap' }}>
        {Object.entries(models).map(([name, m]) => (
          <div key={name} style={{
            background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`,
            borderRadius: 12, padding: 20, flex: 1, minWidth: 250,
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
              <h4 style={{ color: COLORS.white, fontFamily: 'monospace', fontSize: 14, margin: 0 }}>{name}</h4>
              <span style={{ color: COLORS.textMuted, fontFamily: 'monospace', fontSize: 12 }}>
                Вес: {weights[name]}
              </span>
            </div>
            {Object.entries(m).map(([metric, val]) => (
              <div key={metric} style={{ marginBottom: 8 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                  <span style={{ color: COLORS.textMuted, fontFamily: 'monospace', fontSize: 12 }}>{metric.toUpperCase()}</span>
                  <span style={{ color: COLORS.white, fontFamily: 'monospace', fontSize: 12 }}>{val.toFixed(4)}</span>
                </div>
                <ProgressBar value={val} max={1} color={val > 0.9 ? COLORS.green : val > 0.7 ? COLORS.amber : COLORS.red} />
              </div>
            ))}
          </div>
        ))}
      </div>

      {/* Feature Importance */}
      <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, marginBottom: 16 }}>
        <h3 style={{ color: COLORS.white, fontFamily: 'monospace', fontSize: 14, marginBottom: 16 }}>
          Feature Importance (Top-15)
        </h3>
        <ResponsiveContainer width="100%" height={400}>
          <BarChart data={DATA.feature_importance} layout="vertical" margin={{ left: 200 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#1f2937" />
            <XAxis type="number" tick={{ fill: COLORS.textMuted, fontSize: 10 }} />
            <YAxis type="category" dataKey="feature" tick={{ fill: COLORS.textMuted, fontSize: 11 }} width={190} />
            <Tooltip contentStyle={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, fontFamily: 'monospace', fontSize: 12 }} />
            <Bar dataKey="importance" fill={COLORS.blue} radius={[0, 4, 4, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </div>

      {/* Methodology */}
      <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 24 }}>
        <h3 style={{ color: COLORS.white, fontFamily: 'monospace', fontSize: 14, marginBottom: 16 }}>
          Методология
        </h3>
        <div style={{ display: 'flex', gap: 24, flexWrap: 'wrap' }}>
          {[
            { step: '01', title: 'Данные', desc: '36,651 заявок из ГИСС (subsidy.plem.kz). Очистка, парсинг дат, обработка пропусков.' },
            { step: '02', title: 'Feature Engineering', desc: '23 признака: финансовые, временные, региональные, категориальные, конкурентные. LOO-кодирование.' },
            { step: '03', title: 'Ансамбль моделей', desc: 'GB (0.5) + RF (0.3) + LR (0.2). 5-fold CV. Composite merit-score: Efficiency + Reliability + Need + ML.' },
          ].map(s => (
            <div key={s.step} style={{ flex: 1, minWidth: 220 }}>
              <div style={{ color: COLORS.green, fontFamily: 'monospace', fontSize: 24, fontWeight: 700 }}>{s.step}</div>
              <div style={{ color: COLORS.white, fontFamily: 'monospace', fontSize: 14, fontWeight: 600, marginTop: 4 }}>{s.title}</div>
              <div style={{ color: COLORS.textMuted, fontFamily: 'monospace', fontSize: 12, marginTop: 4, lineHeight: 1.5 }}>{s.desc}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function RankingTab() {
  return (
    <div>
      {/* Top-10 Table */}
      <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, marginBottom: 16, overflowX: 'auto' }}>
        <h3 style={{ color: COLORS.white, fontFamily: 'monospace', fontSize: 14, marginBottom: 16 }}>
          Топ-10 заявок по Merit-скору
        </h3>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontFamily: 'monospace', fontSize: 13 }}>
          <thead>
            <tr style={{ borderBottom: `1px solid ${COLORS.cardBorder}` }}>
              {['#', 'Заявка', 'Регион', 'Направление', 'Сумма (₸)', 'Скор', 'Статус'].map(h => (
                <th key={h} style={{ color: COLORS.textMuted, padding: '8px 12px', textAlign: 'left', fontWeight: 600 }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {DATA.top_applications.map((a, i) => (
              <tr key={i} style={{ borderBottom: `1px solid ${COLORS.cardBorder}11` }}>
                <td style={{ color: COLORS.textMuted, padding: '8px 12px' }}>{a.rank}</td>
                <td style={{ color: COLORS.blue, padding: '8px 12px' }}>{a.request_num}</td>
                <td style={{ color: COLORS.text, padding: '8px 12px' }}>{a.region}</td>
                <td style={{ color: COLORS.text, padding: '8px 12px' }}>{a.direction}</td>
                <td style={{ color: COLORS.text, padding: '8px 12px' }}>{a.amount.toLocaleString()}</td>
                <td style={{ color: COLORS.green, padding: '8px 12px', fontWeight: 600 }}>{a.score}</td>
                <td style={{ padding: '8px 12px' }}><Badge level={a.risk_level} /></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Example Explanation */}
      {DATA.example_explain && (
        <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 24 }}>
          <h3 style={{ color: COLORS.white, fontFamily: 'monospace', fontSize: 14, marginBottom: 16 }}>
            Пример объяснения скора
          </h3>
          <div style={{ display: 'flex', gap: 24, flexWrap: 'wrap', marginBottom: 16 }}>
            <div>
              <div style={{ color: COLORS.textMuted, fontFamily: 'monospace', fontSize: 12 }}>Заявка</div>
              <div style={{ color: COLORS.blue, fontFamily: 'monospace', fontSize: 16 }}>{DATA.example_explain.request_num}</div>
            </div>
            <div>
              <div style={{ color: COLORS.textMuted, fontFamily: 'monospace', fontSize: 12 }}>Скор</div>
              <div style={{ color: COLORS.green, fontFamily: 'monospace', fontSize: 16, fontWeight: 700 }}>{DATA.example_explain.score}</div>
            </div>
            <div>
              <div style={{ color: COLORS.textMuted, fontFamily: 'monospace', fontSize: 12 }}>Статус</div>
              <Badge level={DATA.example_explain.risk_level} />
            </div>
            <div>
              <div style={{ color: COLORS.textMuted, fontFamily: 'monospace', fontSize: 12 }}>Регион</div>
              <div style={{ color: COLORS.text, fontFamily: 'monospace', fontSize: 14 }}>{DATA.example_explain.region}</div>
            </div>
            <div>
              <div style={{ color: COLORS.textMuted, fontFamily: 'monospace', fontSize: 12 }}>Сумма</div>
              <div style={{ color: COLORS.text, fontFamily: 'monospace', fontSize: 14 }}>{DATA.example_explain.amount.toLocaleString()} ₸</div>
            </div>
          </div>

          <h4 style={{ color: COLORS.white, fontFamily: 'monospace', fontSize: 13, marginBottom: 12 }}>
            Ключевые факторы:
          </h4>
          {DATA.example_explain.factors.map((f, i) => (
            <div key={i} style={{
              display: 'flex', alignItems: 'center', gap: 12, marginBottom: 8,
              padding: '8px 12px', background: '#0a0f1a', borderRadius: 6,
            }}>
              <span style={{ color: COLORS.textMuted, fontFamily: 'monospace', fontSize: 12, width: 200 }}>
                {f.feature}
              </span>
              <div style={{ flex: 1 }}>
                <ProgressBar value={f.importance} max={0.3} color={COLORS.blue} />
              </div>
              <span style={{ color: COLORS.white, fontFamily: 'monospace', fontSize: 12, width: 60, textAlign: 'right' }}>
                {f.importance.toFixed(4)}
              </span>
            </div>
          ))}

          <div style={{
            marginTop: 16, padding: 12, background: COLORS.green + '11',
            border: `1px solid ${COLORS.green}33`, borderRadius: 8,
          }}>
            <div style={{ color: COLORS.green, fontFamily: 'monospace', fontSize: 12 }}>
              Human-in-the-loop: Система рекомендует — финальное решение принимает комиссия
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// ==================== MAIN APP ====================

const TABS = [
  { id: 'overview', label: 'Обзор' },
  { id: 'regions', label: 'Регионы' },
  { id: 'model', label: 'Модель' },
  { id: 'ranking', label: 'Рейтинг' },
];

export default function App() {
  const [activeTab, setActiveTab] = useState('overview');

  return (
    <div style={{ background: COLORS.bg, minHeight: '100vh', color: COLORS.text, fontFamily: 'monospace' }}>
      {/* Header */}
      <div style={{
        padding: '16px 24px', borderBottom: `1px solid ${COLORS.cardBorder}`,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <span style={{ color: COLORS.green, fontSize: 20, fontWeight: 700 }}>SubsidyScore AI</span>
          <span style={{ color: COLORS.textMuted, fontSize: 12 }}>Merit-Based Scoring System</span>
        </div>
        <div style={{ color: COLORS.textMuted, fontSize: 12 }}>
          Decentrathon 5.0 | AI inDrive | Case 2
        </div>
      </div>

      {/* Tabs */}
      <div style={{ padding: '0 24px', borderBottom: `1px solid ${COLORS.cardBorder}`, display: 'flex', gap: 0 }}>
        {TABS.map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            style={{
              background: 'none', border: 'none', cursor: 'pointer',
              padding: '12px 20px', fontFamily: 'monospace', fontSize: 13,
              color: activeTab === tab.id ? COLORS.green : COLORS.textMuted,
              borderBottom: activeTab === tab.id ? `2px solid ${COLORS.green}` : '2px solid transparent',
              fontWeight: activeTab === tab.id ? 600 : 400,
            }}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Content */}
      <div style={{ padding: 24, maxWidth: 1200, margin: '0 auto' }}>
        {activeTab === 'overview' && <OverviewTab />}
        {activeTab === 'regions' && <RegionsTab />}
        {activeTab === 'model' && <ModelTab />}
        {activeTab === 'ranking' && <RankingTab />}
      </div>
    </div>
  );
}
