import React, { useState } from 'react';
import {
  AreaChart, Area, BarChart, Bar, PieChart, Pie, Cell,
  XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend,
} from 'recharts';

// ==================== DATA (from outputs/dashboard_data.json — generated by pipeline.py) ====================

const DATA = {
  overview: {
    total_applications: 36651,
    avg_score: 72.97,
    total_amount: 139325578572.0,
    recommended: 20740,
    pct_recommended: 56.6,
  },
  score_distribution: [
    { range: '0-5', count: 0 }, { range: '5-10', count: 0 },
    { range: '10-15', count: 0 }, { range: '15-20', count: 0 },
    { range: '20-25', count: 0 }, { range: '25-30', count: 0 },
    { range: '30-35', count: 0 }, { range: '35-40', count: 0 },
    { range: '40-45', count: 1 }, { range: '45-50', count: 33 },
    { range: '50-55', count: 384 }, { range: '55-60', count: 2934 },
    { range: '60-65', count: 6163 }, { range: '65-70', count: 6396 },
    { range: '70-75', count: 5155 }, { range: '75-80', count: 5242 },
    { range: '80-85', count: 5107 }, { range: '85-90', count: 3897 },
    { range: '90-95', count: 1310 }, { range: '95-100', count: 29 },
  ],
  risk_distribution: [
    { level: 'recommended', count: 20740 },
    { level: 'low_risk', count: 15877 },
    { level: 'medium_risk', count: 34 },
  ],
  direction_stats: [
    { direction: 'Коневодство', count: 1382, avg_score: 77.15 },
    { direction: 'Птицеводство', count: 5360, avg_score: 75.41 },
    { direction: 'Свиноводство', count: 116, avg_score: 74.47 },
    { direction: 'Козоводство', count: 3, avg_score: 74.34 },
    { direction: 'Верблюдоводство', count: 1382, avg_score: 74.02 },
    { direction: 'Искусств. осеменение', count: 247, avg_score: 73.10 },
    { direction: 'Овцеводство', count: 3560, avg_score: 72.79 },
    { direction: 'Скотоводство', count: 24397, avg_score: 72.19 },
    { direction: 'Пчеловодство', count: 204, avg_score: 70.33 },
  ],
  region_stats: [
    { region: 'Карагандинская область', count: 926, avg_score: 76.38, recommended: 573, pct_recommended: 61.9 },
    { region: 'Атырауская область', count: 617, avg_score: 76.10, recommended: 349, pct_recommended: 56.6 },
    { region: 'область Ұлытау', count: 360, avg_score: 75.81, recommended: 199, pct_recommended: 55.3 },
    { region: 'Алматинская область', count: 2681, avg_score: 75.06, recommended: 1857, pct_recommended: 69.3 },
    { region: 'область Абай', count: 3683, avg_score: 75.13, recommended: 2378, pct_recommended: 64.6 },
    { region: 'Кызылординская область', count: 1260, avg_score: 74.84, recommended: 787, pct_recommended: 62.5 },
    { region: 'область Жетісу', count: 1479, avg_score: 74.79, recommended: 884, pct_recommended: 59.8 },
    { region: 'Актюбинская область', count: 2385, avg_score: 73.88, recommended: 1317, pct_recommended: 55.2 },
    { region: 'Мангистауская область', count: 3423, avg_score: 73.80, recommended: 2346, pct_recommended: 68.5 },
    { region: 'Костанайская область', count: 2509, avg_score: 73.45, recommended: 1445, pct_recommended: 57.6 },
    { region: 'Овцеводство', count: 3560, avg_score: 72.79, recommended: 0, pct_recommended: 0 },
    { region: 'ВКО', count: 1376, avg_score: 72.67, recommended: 693, pct_recommended: 50.4 },
    { region: 'Жамбылская область', count: 3312, avg_score: 72.46, recommended: 1970, pct_recommended: 59.5 },
    { region: 'Акмолинская область', count: 963, avg_score: 72.08, recommended: 510, pct_recommended: 53.0 },
    { region: 'СКО', count: 1554, avg_score: 71.77, recommended: 808, pct_recommended: 52.0 },
    { region: 'Павлодарская область', count: 2281, avg_score: 70.89, recommended: 927, pct_recommended: 40.6 },
    { region: 'ЗКО', count: 5156, avg_score: 70.41, recommended: 2717, pct_recommended: 52.7 },
    { region: 'Туркестанская область', count: 2281, avg_score: 70.21, recommended: 849, pct_recommended: 37.2 },
    { region: 'г. Шымкент', count: 405, avg_score: 68.79, recommended: 131, pct_recommended: 32.3 },
  ],
  model_results: {
    GradientBoosting: { auc: 0.7472, acc: 0.8661, f1: 0.9279, prec: 0.8675, rec: 0.9974 },
    RandomForest: { auc: 0.7202, acc: 0.8643, f1: 0.9272, prec: 0.8643, rec: 1.0 },
    LogisticRegression: { auc: 0.618, acc: 0.8643, f1: 0.9272, prec: 0.8644, rec: 0.9999 },
  },
  feature_importance: [
    { feature: 'Скорость подачи', importance: 0.003296 },
    { feature: 'Норматив (log)', importance: 0.002243 },
    { feature: 'Заявок в районе', importance: 0.001970 },
    { feature: 'Заявок в регионе', importance: 0.001910 },
    { feature: 'Категория (код)', importance: 0.001097 },
    { feature: 'Заявок в месяце', importance: 0.000682 },
    { feature: 'Регион (код)', importance: 0.000551 },
    { feature: 'Район (код)', importance: 0.000475 },
    { feature: 'День месяца', importance: 0.000278 },
    { feature: 'Расч. единицы (log)', importance: 0.000235 },
    { feature: 'Сумма vs медиана рег.', importance: 0.000235 },
    { feature: 'Сумма запроса (log)', importance: 0.000109 },
    { feature: 'День недели', importance: 0.000065 },
    { feature: 'Направление (код)', importance: 0.000060 },
    { feature: 'Час подачи', importance: 0.000049 },
  ],
  top_applications: [
    { rank: 1, request_num: '1200100307891', region: 'Атырауская обл.', district: 'Исатайский район', direction: 'Скотоводство', amount: 780000, score: 96.21, risk_level: 'recommended' },
    { rank: 2, request_num: '1200100305744', region: 'Атырауская обл.', district: 'Исатайский район', direction: 'Скотоводство', amount: 790000, score: 96.12, risk_level: 'recommended' },
    { rank: 3, request_num: '1200100283989', region: 'Карагандинская обл.', district: 'Бухар-Жырауский р.', direction: 'Скотоводство', amount: 750000, score: 95.96, risk_level: 'recommended' },
    { rank: 4, request_num: '1200100311615', region: 'Атырауская обл.', district: 'Курмангазинский р.', direction: 'Скотоводство', amount: 800000, score: 95.81, risk_level: 'recommended' },
    { rank: 5, request_num: '1200100286608', region: 'Карагандинская обл.', district: 'Шетский район', direction: 'Скотоводство', amount: 740000, score: 95.76, risk_level: 'recommended' },
    { rank: 6, request_num: '1200100297027', region: 'Карагандинская обл.', district: 'Бухар-Жырауский р.', direction: 'Скотоводство', amount: 740000, score: 95.58, risk_level: 'recommended' },
    { rank: 7, request_num: '1200100284994', region: 'область Жетісу', district: 'Панфиловский район', direction: 'Скотоводство', amount: 800000, score: 95.53, risk_level: 'recommended' },
    { rank: 8, request_num: '1200100305812', region: 'Карагандинская обл.', district: 'Актогайский район', direction: 'Скотоводство', amount: 750000, score: 95.51, risk_level: 'recommended' },
    { rank: 9, request_num: '1200100298725', region: 'область Жетісу', district: 'Панфиловский район', direction: 'Скотоводство', amount: 800000, score: 95.41, risk_level: 'recommended' },
    { rank: 10, request_num: '1200100285980', region: 'Карагандинская обл.', district: 'Каркаралинский р.', direction: 'Скотоводство', amount: 840000, score: 95.41, risk_level: 'recommended' },
  ],
  example_explain: {
    request_num: '1200100307891',
    score: 96.21,
    risk_level: 'recommended',
    region: 'Атырауская область',
    direction: 'Скотоводство',
    amount: 780000,
    efficiency_score: 100.0,
    reliability_score: 92.8,
    need_score: 96.4,
    ml_score: 94.6,
    merit_score: 96.2,
    factors: [
      { feature: 'Скорость подачи', importance: 0.0033, description: 'Заявка подана одной из первых — высокая готовность' },
      { feature: 'Норматив', importance: 0.0022, description: 'Норматив соответствует типичным значениям для категории' },
      { feature: 'Заявок в районе', importance: 0.0020, description: 'Район с умеренной конкуренцией (240 заявок)' },
      { feature: 'Заявок в регионе', importance: 0.0019, description: 'Регион со средней активностью (617 заявок)' },
      { feature: 'Категория субсидии', importance: 0.0011, description: 'Скотоводство — основное направление субсидирования' },
    ],
  },
  fifo_vs_merit: {
    fifo_top1000_avg_score: 77.2,
    merit_top1000_avg_score: 92.4,
    fifo_top1000_high_risk_count: 0,
    merit_top1000_high_risk_count: 0,
    fifo_top1000_medium_risk_count: 0,
    merit_top1000_medium_risk_count: 0,
    score_improvement_pct: 19.7,
    budget_efficiency_gain: 'При merit-based подходе 273 заявки с пониженным приоритетом из топ-1000 были бы заменены на рекомендованные. Средний скор вырос бы с 77.2 до 92.4 (+19.7%)',
    risk_comparison: [
      { level: 'recommended', fifo: 727, merit: 1000 },
      { level: 'low_risk', fifo: 273, merit: 0 },
      { level: 'medium_risk', fifo: 0, merit: 0 },
      { level: 'high_risk', fifo: 0, merit: 0 },
    ],
  },
};

// ==================== COLORS ====================
const COLORS = {
  bg: '#0a0f1a',
  card: '#111827',
  cardBorder: '#1e293b',
  green: '#10b981',
  blue: '#3b82f6',
  amber: '#f59e0b',
  red: '#ef4444',
  text: '#e5e7eb',
  textMuted: '#9ca3af',
  white: '#ffffff',
};

const RISK_COLORS = { recommended: COLORS.green, low_risk: COLORS.blue, medium_risk: COLORS.amber, high_risk: COLORS.red };
const RISK_LABELS = { recommended: 'Рекомендована', low_risk: 'Низкий риск', medium_risk: 'Средний риск', high_risk: 'Высокий риск' };
const FONT = { fontFamily: '"JetBrains Mono", monospace' };

// ==================== COMPONENTS ====================

function MetricCard({ title, value, subtitle, color }) {
  return (
    <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: '20px 24px', flex: 1, minWidth: 200 }}>
      <div style={{ color: COLORS.textMuted, fontSize: 13, ...FONT, marginBottom: 8 }}>{title}</div>
      <div style={{ color: color || COLORS.white, fontSize: 28, fontWeight: 700, ...FONT }}>{value}</div>
      {subtitle && <div style={{ color: COLORS.textMuted, fontSize: 12, ...FONT, marginTop: 4 }}>{subtitle}</div>}
    </div>
  );
}

function Badge({ level }) {
  const color = RISK_COLORS[level] || COLORS.textMuted;
  return (
    <span style={{ display: 'inline-block', padding: '2px 10px', borderRadius: 6, background: color + '22', color, fontSize: 12, ...FONT, fontWeight: 600 }}>
      {RISK_LABELS[level] || level}
    </span>
  );
}

function ProgressBar({ value, max, color }) {
  const pct = max > 0 ? (value / max * 100) : 0;
  return (
    <div style={{ background: '#1f2937', borderRadius: 4, height: 8, width: '100%' }}>
      <div style={{ background: color || COLORS.green, borderRadius: 4, height: 8, width: `${Math.min(pct, 100)}%`, transition: 'width 0.3s' }} />
    </div>
  );
}

// ==================== TABS ====================

function OverviewTab() {
  const o = DATA.overview;
  return (
    <div>
      <div style={{ display: 'flex', gap: 16, marginBottom: 24, flexWrap: 'wrap' }}>
        <MetricCard title="ВСЕГО ЗАЯВОК" value={o.total_applications.toLocaleString()} />
        <MetricCard title="СРЕДНИЙ MERIT-СКОР" value={o.avg_score} color={COLORS.green} />
        <MetricCard title="ОБЩАЯ СУММА" value={`${(o.total_amount / 1e9).toFixed(1)} млрд ₸`} color={COLORS.blue} />
        <MetricCard title="РЕКОМЕНДОВАНО" value={`${o.pct_recommended}%`} subtitle={`${o.recommended.toLocaleString()} заявок`} color={COLORS.green} />
      </div>
      <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap' }}>
        <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, flex: 2, minWidth: 400 }}>
          <h3 style={{ color: COLORS.white, ...FONT, fontSize: 14, marginBottom: 16, marginTop: 0 }}>Распределение Merit-скоров</h3>
          <ResponsiveContainer width="100%" height={250}>
            <AreaChart data={DATA.score_distribution}>
              <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
              <XAxis dataKey="range" tick={{ fill: COLORS.textMuted, fontSize: 10 }} />
              <YAxis tick={{ fill: COLORS.textMuted, fontSize: 10 }} />
              <Tooltip contentStyle={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, ...FONT, fontSize: 12 }} />
              <Area type="monotone" dataKey="count" stroke={COLORS.green} fill={COLORS.green + '33'} name="Заявок" />
            </AreaChart>
          </ResponsiveContainer>
        </div>
        <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, flex: 1, minWidth: 280 }}>
          <h3 style={{ color: COLORS.white, ...FONT, fontSize: 14, marginBottom: 16, marginTop: 0 }}>Распределение рисков</h3>
          <ResponsiveContainer width="100%" height={250}>
            <PieChart>
              <Pie data={DATA.risk_distribution} dataKey="count" nameKey="level" cx="50%" cy="50%" innerRadius={50} outerRadius={80}
                label={({ level, count }) => `${RISK_LABELS[level]}: ${count.toLocaleString()}`}>
                {DATA.risk_distribution.map((entry, i) => <Cell key={i} fill={RISK_COLORS[entry.level]} />)}
              </Pie>
              <Tooltip contentStyle={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, ...FONT, fontSize: 12 }} />
            </PieChart>
          </ResponsiveContainer>
        </div>
      </div>
      <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, marginTop: 16 }}>
        <h3 style={{ color: COLORS.white, ...FONT, fontSize: 14, marginBottom: 16, marginTop: 0 }}>Средний скор по направлениям</h3>
        <ResponsiveContainer width="100%" height={320}>
          <BarChart data={DATA.direction_stats} layout="vertical" margin={{ left: 160 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
            <XAxis type="number" domain={[65, 80]} tick={{ fill: COLORS.textMuted, fontSize: 10 }} />
            <YAxis type="category" dataKey="direction" tick={{ fill: COLORS.textMuted, fontSize: 11 }} width={150} />
            <Tooltip contentStyle={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, ...FONT, fontSize: 12 }} />
            <Bar dataKey="avg_score" fill={COLORS.blue} radius={[0, 4, 4, 0]} name="Средний скор" />
          </BarChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}

function RegionsTab() {
  const sorted = [...DATA.region_stats].filter(r => r.pct_recommended > 0).sort((a, b) => b.avg_score - a.avg_score);
  return (
    <div>
      <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, marginBottom: 16 }}>
        <h3 style={{ color: COLORS.white, ...FONT, fontSize: 14, marginBottom: 16, marginTop: 0 }}>Средний Merit-скор по регионам</h3>
        <ResponsiveContainer width="100%" height={520}>
          <BarChart data={sorted} layout="vertical" margin={{ left: 200 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
            <XAxis type="number" domain={[65, 80]} tick={{ fill: COLORS.textMuted, fontSize: 10 }} />
            <YAxis type="category" dataKey="region" tick={{ fill: COLORS.textMuted, fontSize: 11 }} width={190} />
            <Tooltip contentStyle={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, ...FONT, fontSize: 12 }} />
            <Bar dataKey="avg_score" radius={[0, 4, 4, 0]} name="Средний скор">
              {sorted.map((entry, i) => <Cell key={i} fill={entry.avg_score >= 75 ? COLORS.green : entry.avg_score >= 72 ? COLORS.blue : COLORS.amber} />)}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </div>
      <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, overflowX: 'auto' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', ...FONT, fontSize: 13 }}>
          <thead>
            <tr style={{ borderBottom: `1px solid ${COLORS.cardBorder}` }}>
              {['Регион', 'Сред. скор', 'Заявок', 'Рекомендовано', '% рекоменд.', ''].map(h =>
                <th key={h} style={{ color: COLORS.textMuted, padding: '8px 12px', textAlign: 'left', fontWeight: 600 }}>{h}</th>
              )}
            </tr>
          </thead>
          <tbody>
            {sorted.map((r, i) => (
              <tr key={i} style={{ borderBottom: `1px solid ${COLORS.cardBorder}22` }}>
                <td style={{ color: COLORS.text, padding: '8px 12px' }}>{r.region}</td>
                <td style={{ color: r.avg_score >= 75 ? COLORS.green : r.avg_score >= 72 ? COLORS.blue : COLORS.amber, padding: '8px 12px', fontWeight: 600 }}>{r.avg_score}</td>
                <td style={{ color: COLORS.text, padding: '8px 12px' }}>{r.count.toLocaleString()}</td>
                <td style={{ color: COLORS.text, padding: '8px 12px' }}>{r.recommended.toLocaleString()}</td>
                <td style={{ color: COLORS.text, padding: '8px 12px' }}>{r.pct_recommended}%</td>
                <td style={{ padding: '8px 12px', minWidth: 100 }}>
                  <ProgressBar value={r.pct_recommended} max={100} color={r.avg_score >= 75 ? COLORS.green : r.avg_score >= 72 ? COLORS.blue : COLORS.amber} />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function ModelTab() {
  const models = DATA.model_results;
  const meta = { GradientBoosting: { weight: 0.5, role: 'Primary' }, RandomForest: { weight: 0.3, role: 'Secondary' }, LogisticRegression: { weight: 0.2, role: 'Baseline' } };
  const metricLabels = { auc: 'AUC', acc: 'Accuracy', f1: 'F1-Score' };
  return (
    <div>
      <div style={{ display: 'flex', gap: 16, marginBottom: 24, flexWrap: 'wrap' }}>
        {Object.entries(models).map(([name, m]) => (
          <div key={name} style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, flex: 1, minWidth: 280 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
              <h4 style={{ color: COLORS.white, ...FONT, fontSize: 14, margin: 0 }}>{name}</h4>
              <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                <span style={{
                  padding: '2px 8px', borderRadius: 4, fontSize: 11, ...FONT, fontWeight: 600,
                  background: meta[name].role === 'Primary' ? COLORS.green + '22' : meta[name].role === 'Baseline' ? COLORS.amber + '22' : COLORS.blue + '22',
                  color: meta[name].role === 'Primary' ? COLORS.green : meta[name].role === 'Baseline' ? COLORS.amber : COLORS.blue,
                }}>{meta[name].role}</span>
                <span style={{ color: COLORS.textMuted, ...FONT, fontSize: 12 }}>w={meta[name].weight}</span>
              </div>
            </div>
            {['auc', 'acc', 'f1'].map(metric => (
              <div key={metric} style={{ marginBottom: 10 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                  <span style={{ color: COLORS.textMuted, ...FONT, fontSize: 12 }}>{metricLabels[metric]}</span>
                  <span style={{ color: COLORS.white, ...FONT, fontSize: 12, fontWeight: 600 }}>{m[metric].toFixed(4)}</span>
                </div>
                <ProgressBar value={m[metric]} max={1} color={m[metric] > 0.85 ? COLORS.green : m[metric] > 0.7 ? COLORS.blue : COLORS.amber} />
              </div>
            ))}
          </div>
        ))}
      </div>
      <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, marginBottom: 16 }}>
        <h3 style={{ color: COLORS.white, ...FONT, fontSize: 14, marginBottom: 16, marginTop: 0 }}>Feature Importance (Top-15)</h3>
        <ResponsiveContainer width="100%" height={420}>
          <BarChart data={DATA.feature_importance} layout="vertical" margin={{ left: 180 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
            <XAxis type="number" tick={{ fill: COLORS.textMuted, fontSize: 10 }} />
            <YAxis type="category" dataKey="feature" tick={{ fill: COLORS.textMuted, fontSize: 11 }} width={170} />
            <Tooltip contentStyle={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, ...FONT, fontSize: 12 }} />
            <Bar dataKey="importance" fill={COLORS.blue} radius={[0, 4, 4, 0]} name="Важность" />
          </BarChart>
        </ResponsiveContainer>
      </div>
      <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 24 }}>
        <h3 style={{ color: COLORS.white, ...FONT, fontSize: 14, marginBottom: 16, marginTop: 0 }}>Методология</h3>
        <div style={{ display: 'flex', gap: 24, flexWrap: 'wrap' }}>
          {[
            { step: '01', title: 'Данные', desc: '36,651 заявок из ГИСС (subsidy.plem.kz). Очистка, парсинг дат, обработка пропусков. Target: одобрена (86.4%) vs отклонена (13.6%).' },
            { step: '02', title: 'Feature Engineering', desc: '23 признака в 5 группах: финансовые, временные, региональные, категориальные, конкурентные. LOO-Bayesian кодирование.' },
            { step: '03', title: 'Ансамбль + Merit', desc: 'GB (0.5) + RF (0.3) + LR (0.2) -> ML Score. Композитный Merit = 0.3*Efficiency + 0.2*Reliability + 0.2*Need + 0.3*ML.' },
          ].map(s => (
            <div key={s.step} style={{ flex: 1, minWidth: 240 }}>
              <div style={{ color: COLORS.green, ...FONT, fontSize: 28, fontWeight: 700 }}>{s.step}</div>
              <div style={{ color: COLORS.white, ...FONT, fontSize: 14, fontWeight: 600, marginTop: 4 }}>{s.title}</div>
              <div style={{ color: COLORS.textMuted, ...FONT, fontSize: 12, marginTop: 6, lineHeight: 1.6 }}>{s.desc}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function RankingTab() {
  const ex = DATA.example_explain;
  return (
    <div>
      <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, marginBottom: 16, overflowX: 'auto' }}>
        <h3 style={{ color: COLORS.white, ...FONT, fontSize: 14, marginBottom: 16, marginTop: 0 }}>Топ-10 заявок по Merit-скору</h3>
        <table style={{ width: '100%', borderCollapse: 'collapse', ...FONT, fontSize: 13 }}>
          <thead>
            <tr style={{ borderBottom: `1px solid ${COLORS.cardBorder}` }}>
              {['#', 'Заявка', 'Регион', 'Район', 'Направление', 'Сумма (₸)', 'Merit', 'Статус'].map(h =>
                <th key={h} style={{ color: COLORS.textMuted, padding: '8px 10px', textAlign: 'left', fontWeight: 600 }}>{h}</th>
              )}
            </tr>
          </thead>
          <tbody>
            {DATA.top_applications.map((a, i) => (
              <tr key={i} style={{ borderBottom: `1px solid ${COLORS.cardBorder}22` }}>
                <td style={{ color: COLORS.textMuted, padding: '8px 10px' }}>{a.rank}</td>
                <td style={{ color: COLORS.blue, padding: '8px 10px', fontSize: 12 }}>{a.request_num}</td>
                <td style={{ color: COLORS.text, padding: '8px 10px', fontSize: 12 }}>{a.region}</td>
                <td style={{ color: COLORS.textMuted, padding: '8px 10px', fontSize: 12 }}>{a.district}</td>
                <td style={{ color: COLORS.text, padding: '8px 10px', fontSize: 12 }}>{a.direction}</td>
                <td style={{ color: COLORS.text, padding: '8px 10px' }}>{a.amount.toLocaleString()}</td>
                <td style={{ color: COLORS.green, padding: '8px 10px', fontWeight: 700 }}>{a.score}</td>
                <td style={{ padding: '8px 10px' }}><Badge level={a.risk_level} /></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {ex && (
        <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 24, marginBottom: 16 }}>
          <h3 style={{ color: COLORS.white, ...FONT, fontSize: 14, marginBottom: 16, marginTop: 0 }}>Пример объяснения скора (Explainability)</h3>
          <div style={{ display: 'flex', gap: 20, flexWrap: 'wrap', marginBottom: 20 }}>
            {[
              { label: 'Заявка', val: ex.request_num, color: COLORS.blue },
              { label: 'Merit Score', val: ex.score, color: COLORS.green, bold: true },
              { label: 'Регион', val: ex.region, color: COLORS.text },
              { label: 'Сумма', val: `${ex.amount.toLocaleString()} ₸`, color: COLORS.text },
            ].map(item => (
              <div key={item.label}>
                <div style={{ color: COLORS.textMuted, ...FONT, fontSize: 11 }}>{item.label}</div>
                <div style={{ color: item.color, ...FONT, fontSize: item.bold ? 20 : 14, fontWeight: item.bold ? 700 : 400 }}>{item.val}</div>
              </div>
            ))}
            <div><div style={{ color: COLORS.textMuted, ...FONT, fontSize: 11 }}>Статус</div><Badge level={ex.risk_level} /></div>
          </div>
          <h4 style={{ color: COLORS.white, ...FONT, fontSize: 13, marginBottom: 12 }}>Компоненты Merit Score:</h4>
          <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 20 }}>
            {[
              { label: 'Efficiency', value: ex.efficiency_score, desc: 'Адекватность запроса', color: COLORS.green },
              { label: 'Reliability', value: ex.reliability_score, desc: 'Надёжность заявителя', color: COLORS.blue },
              { label: 'Need', value: ex.need_score, desc: 'Потребность региона', color: COLORS.amber },
              { label: 'ML Score', value: ex.ml_score, desc: 'Прогноз модели', color: COLORS.green },
            ].map(c => (
              <div key={c.label} style={{ flex: 1, minWidth: 140, padding: 12, background: '#0a0f1a', borderRadius: 8, border: `1px solid ${COLORS.cardBorder}` }}>
                <div style={{ color: COLORS.textMuted, ...FONT, fontSize: 11 }}>{c.label}</div>
                <div style={{ color: c.color, ...FONT, fontSize: 22, fontWeight: 700, marginTop: 4 }}>{c.value}</div>
                <div style={{ color: COLORS.textMuted, ...FONT, fontSize: 10, marginTop: 2 }}>{c.desc}</div>
              </div>
            ))}
          </div>
          <h4 style={{ color: COLORS.white, ...FONT, fontSize: 13, marginBottom: 12 }}>Ключевые факторы:</h4>
          {ex.factors.map((f, i) => (
            <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 8, padding: '10px 12px', background: '#0a0f1a', borderRadius: 6 }}>
              <span style={{ color: COLORS.text, ...FONT, fontSize: 12, width: 180, flexShrink: 0 }}>{f.feature}</span>
              <div style={{ flex: 1 }}><ProgressBar value={f.importance} max={0.004} color={COLORS.blue} /></div>
              <span style={{ color: COLORS.textMuted, ...FONT, fontSize: 11, width: 260, textAlign: 'right', flexShrink: 0 }}>{f.description}</span>
            </div>
          ))}
        </div>
      )}
      <div style={{ padding: 16, background: COLORS.green + '11', border: `1px solid ${COLORS.green}33`, borderRadius: 8 }}>
        <div style={{ color: COLORS.green, ...FONT, fontSize: 13, fontWeight: 600, marginBottom: 4 }}>Human-in-the-Loop</div>
        <div style={{ color: COLORS.textMuted, ...FONT, fontSize: 12, lineHeight: 1.6 }}>
          Система формирует рейтинг и рекомендации на основе данных. Финальное решение о выдаче субсидии принимает комиссия. AI-скоринг является инструментом поддержки принятия решений, а не заменой экспертного суждения.
        </div>
      </div>
    </div>
  );
}

function FifoMeritTab() {
  const fm = DATA.fifo_vs_merit;
  return (
    <div>
      <div style={{ display: 'flex', gap: 16, marginBottom: 24, flexWrap: 'wrap' }}>
        <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 24, flex: 1, minWidth: 250, textAlign: 'center' }}>
          <div style={{ color: COLORS.textMuted, ...FONT, fontSize: 12, marginBottom: 8 }}>FIFO (по дате) — топ 1000</div>
          <div style={{ color: COLORS.amber, ...FONT, fontSize: 42, fontWeight: 700 }}>{fm.fifo_top1000_avg_score}</div>
          <div style={{ color: COLORS.textMuted, ...FONT, fontSize: 12, marginTop: 4 }}>средний Merit-скор</div>
        </div>
        <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 24, flex: 1, minWidth: 250, textAlign: 'center' }}>
          <div style={{ color: COLORS.textMuted, ...FONT, fontSize: 12, marginBottom: 8 }}>MERIT (по скору) — топ 1000</div>
          <div style={{ color: COLORS.green, ...FONT, fontSize: 42, fontWeight: 700 }}>{fm.merit_top1000_avg_score}</div>
          <div style={{ color: COLORS.textMuted, ...FONT, fontSize: 12, marginTop: 4 }}>средний Merit-скор</div>
        </div>
        <div style={{ background: COLORS.card, border: `1px solid ${COLORS.green}44`, borderRadius: 12, padding: 24, flex: 1, minWidth: 200, textAlign: 'center' }}>
          <div style={{ color: COLORS.textMuted, ...FONT, fontSize: 12, marginBottom: 8 }}>УЛУЧШЕНИЕ</div>
          <div style={{ color: COLORS.green, ...FONT, fontSize: 42, fontWeight: 700 }}>+{fm.score_improvement_pct}%</div>
          <div style={{ color: COLORS.textMuted, ...FONT, fontSize: 12, marginTop: 4 }}>рост среднего скора</div>
        </div>
      </div>
      <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, marginBottom: 16 }}>
        <h3 style={{ color: COLORS.white, ...FONT, fontSize: 14, marginBottom: 16, marginTop: 0 }}>Распределение рисков в топ-1000: FIFO vs Merit</h3>
        <ResponsiveContainer width="100%" height={250}>
          <BarChart data={fm.risk_comparison} margin={{ left: 20 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
            <XAxis dataKey="level" tick={{ fill: COLORS.textMuted, fontSize: 11 }} tickFormatter={l => RISK_LABELS[l] || l} />
            <YAxis tick={{ fill: COLORS.textMuted, fontSize: 10 }} />
            <Tooltip contentStyle={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, ...FONT, fontSize: 12 }} labelFormatter={l => RISK_LABELS[l] || l} />
            <Legend wrapperStyle={{ ...FONT, fontSize: 12 }} />
            <Bar dataKey="fifo" fill={COLORS.amber} name="FIFO (по дате)" radius={[4, 4, 0, 0]} />
            <Bar dataKey="merit" fill={COLORS.green} name="Merit (по скору)" radius={[4, 4, 0, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </div>
      <div style={{ display: 'flex', gap: 16, marginBottom: 16, flexWrap: 'wrap' }}>
        <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, flex: 1 }}>
          <h4 style={{ color: COLORS.amber, ...FONT, fontSize: 13, marginTop: 0 }}>FIFO (текущий подход)</h4>
          <div style={{ color: COLORS.textMuted, ...FONT, fontSize: 12, lineHeight: 1.8 }}>
            <div>Рекомендовано: <span style={{ color: COLORS.white }}>{fm.risk_comparison[0].fifo}</span> из 1000</div>
            <div>Низкий риск: <span style={{ color: COLORS.blue }}>{fm.risk_comparison[1].fifo}</span></div>
            <div>Средний/высокий риск: <span style={{ color: COLORS.amber }}>{fm.risk_comparison[2].fifo + fm.risk_comparison[3].fifo}</span></div>
          </div>
        </div>
        <div style={{ background: COLORS.card, border: `1px solid ${COLORS.cardBorder}`, borderRadius: 12, padding: 20, flex: 1 }}>
          <h4 style={{ color: COLORS.green, ...FONT, fontSize: 13, marginTop: 0 }}>Merit (наш подход)</h4>
          <div style={{ color: COLORS.textMuted, ...FONT, fontSize: 12, lineHeight: 1.8 }}>
            <div>Рекомендовано: <span style={{ color: COLORS.green, fontWeight: 700 }}>{fm.risk_comparison[0].merit}</span> из 1000</div>
            <div>Низкий риск: <span style={{ color: COLORS.white }}>{fm.risk_comparison[1].merit}</span></div>
            <div>Средний/высокий риск: <span style={{ color: COLORS.white }}>{fm.risk_comparison[2].merit + fm.risk_comparison[3].merit}</span></div>
          </div>
        </div>
      </div>
      <div style={{ padding: 16, background: COLORS.green + '11', border: `1px solid ${COLORS.green}33`, borderRadius: 8 }}>
        <div style={{ color: COLORS.green, ...FONT, fontSize: 13, fontWeight: 600, marginBottom: 6 }}>Вывод</div>
        <div style={{ color: COLORS.text, ...FONT, fontSize: 12, lineHeight: 1.6 }}>{fm.budget_efficiency_gain}</div>
      </div>
    </div>
  );
}

// ==================== MAIN APP ====================
const TABS = [
  { id: 'overview', label: 'Обзор' },
  { id: 'regions', label: 'Регионы' },
  { id: 'model', label: 'Модель' },
  { id: 'ranking', label: 'Рейтинг' },
  { id: 'fifo', label: 'FIFO vs Merit' },
];

export default function App() {
  const [activeTab, setActiveTab] = useState('overview');
  return (
    <div style={{ background: COLORS.bg, minHeight: '100vh', color: COLORS.text, ...FONT }}>
      <div style={{ padding: '16px 24px', borderBottom: `1px solid ${COLORS.cardBorder}`, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <span style={{ color: COLORS.green, fontSize: 20, fontWeight: 700 }}>SubsidyScore AI</span>
          <span style={{ color: COLORS.textMuted, fontSize: 12 }}>Merit-Based Scoring System</span>
        </div>
        <div style={{ color: COLORS.textMuted, fontSize: 12 }}>Decentrathon 5.0 | AI inDrive | Case 2</div>
      </div>
      <div style={{ padding: '0 24px', borderBottom: `1px solid ${COLORS.cardBorder}`, display: 'flex', gap: 0 }}>
        {TABS.map(tab => (
          <button key={tab.id} onClick={() => setActiveTab(tab.id)} style={{
            background: 'none', border: 'none', cursor: 'pointer', padding: '12px 20px', ...FONT, fontSize: 13,
            color: activeTab === tab.id ? COLORS.green : COLORS.textMuted,
            borderBottom: activeTab === tab.id ? `2px solid ${COLORS.green}` : '2px solid transparent',
            fontWeight: activeTab === tab.id ? 600 : 400,
          }}>{tab.label}</button>
        ))}
      </div>
      <div style={{ padding: 24, maxWidth: 1200, margin: '0 auto' }}>
        {activeTab === 'overview' && <OverviewTab />}
        {activeTab === 'regions' && <RegionsTab />}
        {activeTab === 'model' && <ModelTab />}
        {activeTab === 'ranking' && <RankingTab />}
        {activeTab === 'fifo' && <FifoMeritTab />}
      </div>
    </div>
  );
}
